from typing import Protocol

from app.domain.entities.notification import Notification


class NotificationRepository(Protocol):
    async def get_by_id(self, id: int) -> Notification | None: ...
    async def save(self, notification: Notification) -> Notification: ...
    async def list_by_profile(self, profile_id: int, limit: int = 50) -> list[Notification]: ...
    async def mark_read(self, notification_id: int) -> None: ...
    async def list_unsent(self) -> list[Notification]: ...
