from typing import Protocol

from app.domain.entities.opportunity import Opportunity
from app.domain.enums import OpportunityType


class OpportunityRepository(Protocol):
    async def get_by_id(self, id: int) -> Opportunity | None: ...
    async def get_by_fingerprint(self, fingerprint: str) -> Opportunity | None: ...
    async def save(self, opportunity: Opportunity) -> Opportunity: ...
    async def update(self, opportunity: Opportunity) -> Opportunity: ...
    async def list_active(
        self,
        limit: int = 50,
        offset: int = 0,
        opportunity_type: OpportunityType | None = None,
        organization_id: int | None = None,
    ) -> list[Opportunity]: ...
    async def search(self, query: str, limit: int = 50) -> list[Opportunity]: ...
    async def count_active(self) -> int: ...
    async def mark_inactive_by_source(self, source_id: int, except_ids: list[int]) -> int: ...
