from typing import Protocol

from app.domain.entities.organization import Organization


class OrganizationRepository(Protocol):
    async def get_by_id(self, id: int) -> Organization | None: ...
    async def get_by_name(self, name: str) -> Organization | None: ...
    async def save(self, org: Organization) -> Organization: ...
    async def update(self, org: Organization) -> Organization: ...
    async def list_all(self, limit: int = 200) -> list[Organization]: ...
    async def search(self, query: str, limit: int = 50) -> list[Organization]: ...
