from typing import Protocol

from app.domain.entities.professor import Professor


class ProfessorRepository(Protocol):
    async def get_by_id(self, id: int) -> Professor | None: ...
    async def get_by_organization(self, organization_id: int) -> list[Professor]: ...
    async def save(self, professor: Professor) -> Professor: ...
    async def update(self, professor: Professor) -> Professor: ...
    async def list_accepting_students(self) -> list[Professor]: ...
