from typing import Protocol

from app.domain.entities.scrape_job import ScrapeJob
from app.domain.entities.scrape_result import ScrapeResult


class ScrapeJobRepository(Protocol):
    async def get_by_id(self, id: int) -> ScrapeJob | None: ...
    async def save(self, job: ScrapeJob) -> ScrapeJob: ...
    async def update(self, job: ScrapeJob) -> ScrapeJob: ...
    async def list_recent(self, source_id: int | None = None, limit: int = 20) -> list[ScrapeJob]: ...
    async def save_result(self, result: ScrapeResult) -> ScrapeResult: ...
    async def list_results(self, job_id: int) -> list[ScrapeResult]: ...
