from typing import Protocol

from app.domain.entities.skill import Skill
from app.domain.enums import SkillCategory


class SkillRepository(Protocol):
    async def get_by_id(self, id: int) -> Skill | None: ...
    async def get_by_name(self, name: str) -> Skill | None: ...
    async def get_or_create(self, name: str, category: SkillCategory) -> Skill: ...
    async def save(self, skill: Skill) -> Skill: ...
    async def list_all(self) -> list[Skill]: ...
