from typing import Protocol

from app.domain.entities.source import Source


class SourceRepository(Protocol):
    async def get_by_id(self, id: int) -> Source | None: ...
    async def get_all_active(self) -> list[Source]: ...
    async def get_due_for_scrape(self) -> list[Source]: ...
    async def save(self, source: Source) -> Source: ...
    async def update(self, source: Source) -> Source: ...
    async def touch_last_scraped(self, source_id: int) -> None: ...
