from typing import Protocol

from app.domain.entities.user_profile import UserProfile


class UserProfileRepository(Protocol):
    async def get_by_id(self, id: int) -> UserProfile | None: ...
    async def get_by_user_id(self, user_id: int) -> UserProfile | None: ...
    async def save(self, profile: UserProfile) -> UserProfile: ...
    async def update(self, profile: UserProfile) -> UserProfile: ...
